game:
  name: Crazy Time
  platform: draftkings
  asset_dir: assets/crazy_time/
elements:
  betting_open: betting_open.png
  # reality_check: reality_check.png    # Capture with: --update-asset reality_check
regions: {}
bets:
- segment: '1'
  click_x: 279
  click_y: 638
settings:
  confidence: 0.85
  action_delay:
  - 0.3
  - 1.0
  poll_interval: 2.0
  session_duration: 60
  # reality_check_click:                  # Where to click to dismiss (omit to click matched image)
  #   x: 500
  #   y: 400
