game:
  name: Infinite Blackjack
  platform: fanduel
  asset_dir: assets/infinite_blackjack/
elements:
  betting_open: betting_open.png
  chip_1: chip_1.png
  hit_button: hit_button.png
  stand_button: stand_button.png
  double_button: double_button.png
regions:
  balance:
    x: 90
    y: 652
    w: 31
    h: 14
  player_total:
    x: 343
    y: 622
    w: 16
    h: 10
  dealer_total:
    x: 241
    y: 534
    w: 15
    h: 11
bet_spot:
  x: 377
  y: 620
settings:
  confidence: 0.8
  action_delay:
  - 0.2
  - 0.5
  poll_interval: 1.0
  session_duration: 60
