game:
  name: Infinite Blackjack
  platform: fanduel
  asset_dir: assets/infinite_blackjack/
elements:
  chip_tray: chip_tray.png
  chip_1: chip_1.png
  hit_button: hit_button.png
  stand_button: stand_button.png
  double_button: double_button.png
regions:
  balance:
    x: 92
    y: 657
    w: 32
    h: 8
  player_total:
    x: 339
    y: 619
    w: 23
    h: 15
  dealer_total:
    x: 236
    y: 533
    w: 28
    h: 13
bet_spot:
  x: 377
  y: 620
settings:
  confidence: 0.8
  action_delay:
  - 0.2
  - 0.5
  poll_interval: 1.0
  session_duration: 60
