game:
  name: Infinite Blackjack
  platform: fanduel
  asset_dir: assets/infinite_blackjack/
elements:
  chip_tray: chip_tray.png
  chip_1: chip_1.png
  hit_button: hit_button.png
  stand_button: stand_button.png
  double_button: double_button.png
  reality_check: reality_check.png
regions:
  balance:
    x: 107
    y: 770
    w: 48
    h: 17
  player_total:
    x: 543
    y: 713
    w: 19
    h: 12
  dealer_total:
    x: 367
    y: 562
    w: 18
    h: 10
bet_spot:
  x: 602
  y: 700
settings:
  confidence: 0.8
  action_delay:
  - 0.2
  - 0.5
  poll_interval: 1.0
  session_duration: 60
